fetchsingular: verify MD5 of tarball

diff --git a/fetchsingular b/fetchsingular
--- a/fetchsingular
+++ b/fetchsingular
@@ -26,9 +26,28 @@ else
     exit 1
 fi
 
-# Extract...
+# Verify checksum
+echo "Verifying MD5 checksum of $TARFILE..."
+if command -v md5 >/dev/null 2>&1 ; then
+    COMPUTED_MD5=`md5 $TARFILE`
+elif command -v md5sum >/dev/null 2>&1 ; then
+    COMPUTED_MD5=`md5sum $TARFILE`
+elif command -v openssl >/dev/null 2>&1 ; then
+    COMPUTED_MD5=`openssl md5 $TARFILE`
+else
+    COMPUTED_MD5=skip
+fi
+case $COMPUTED_MD5 in
+   skip) echo "   could not compute MD5 checksum, skipping test" ;;
+   *$MD5* ) echo "   valid MD5 checksum" ;;
+   *)  echo "  invalid MD5 checksum, aborting"
+       exit 1
+       ;;
+esac
+
+# Extract
 tar xvf $TARFILE
 
-# ... and move the output
+# Move output to right place
 rm -rf singular/src
 mv singular-$VERSION singular/src
